### ISSUE TITLE
Adjust website content to vendor name change

### ISSUE THREAD

**Issue by robertlemke** [neos/Neos.NeosIo#117]
We need to revise all content and screenshots on www.neos.io to match the change of the vendor namespace  from:

- "TYPO3" to "Neos"
- "TypoScript" to "Fusion".

Content changes should be collected in a shared workspace and be published on the Neos 3.0 release day.

Details about the namespace change can be found via the umbrella issue https://github.com/neos/neos-development-collection/issues/1240. If questions arise, please contact @johannessteu @robertlemke @kdambekalns @kitsunet or @mgoldbeck.

**Comment by mgoldbeck** [comment]
The changes could be reviewed in the shared workspace "removetypo3"

**Comment by Sebobo** [comment]
@mgoldbeck are those changes published by now? I don't see the workspace `removetypo3` anymore.

**Comment by mgoldbeck** [comment]
already solved
