### ISSUE TITLE
Layout issues on small screens

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#121]
On a Macbook12 the site has some layout issues.

Menu rendering:

<img width="1275" alt="screen_shot_2016-11-23_at_21 20 29" src="https://cloud.githubusercontent.com/assets/95873/20579815/34c6b112-b1cf-11e6-8bb9-cc2aa4c546b1.png">

Text flow issue:

<img width="1252" alt="screen_shot_2016-11-23_at_21 25 33_2" src="https://cloud.githubusercontent.com/assets/95873/20579818/3801bbec-b1cf-11e6-91af-2f4c405d3ddf.png">

**Comment by bwaidelich** [comment]
Related to "layout issues on smaller screens", the navigation overlaps with the logo since we added a new item "events":
![image](https://cloud.githubusercontent.com/assets/307571/20595558/a619acbe-b23a-11e6-906e-5659e2dd455c.png)
