### ISSUE TITLE
XML sitemap contains links to broken pages

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#123]
Examples are the showcase links, there might be more.

The sitemap has been added in #120

**Comment by kdambekalns** [comment]
Another interesting one: https://www.neos.io/features/--.html

**Comment by bwaidelich** [comment]
IMO we should mark show cases "hide in menus" by default

**Comment by bwaidelich** [comment]
> Another interesting one: https://www.neos.io/features/--.html

Wow, really? We re-introduced the "spacer" page type?! ;)

**Comment by Sebobo** [comment]
I'll look into it, thanks for spotting!
