### ISSUE TITLE
Build static css/js files when deploying

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#144]
The following steps need to be executed to build the files correctly:

* Use nodejs 4.2.2
* in Packages/Sites/Neos.NeosIo run `npm install`
* in Packages/Sites/Neos.NeosIo run `npm run build`
* ~~in Packages/Application/Neos.MarketPlace run `npm install`~~ Included in #125 

ToDos:

- [ ] CSS/JS files not in git anymore
- [ ] CSS/JS files are built when deploying a new version

The build process is detailed [here](https://github.com/neos/Neos.NeosIo/blob/master/README.md)

**Comment by robertlemke** [comment]
Hmm, to me it looks like the build is a bit broken at the moment, at least it doesn't work for me right now:

```
> neos-io@0.0.1 build:sass /build/Packages/Sites/Neos.NeosIo
> node-sass Resources/Private/Scss/ -o Resources/Public/Styles/

{
  "formatted": "Error: File to import not found or unreadable: Atoms/_EventCosts\n       Parent style sheet: /build/Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Main.scss\n        on line 49 of Resources/Private/Scss/Main.scss\n>> @import 'Atoms/_EventCosts';\n   ^\n",
  "message": "File to import not found or unreadable: Atoms/_EventCosts\nParent style sheet: /build/Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Main.scss",
  "column": 1,
  "line": 49,
  "file": "/build/Packages/Sites/Neos.NeosIo/Resources/Private/Scss/Main.scss",
  "status": 1
}

npm ERR! Linux 4.4.39-moby
npm ERR! argv "/root/.nvm/versions/node/v4.2.2/bin/node" "/root/.nvm/versions/node/v4.2.2/bin/npm" "run" "build:sass"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
```

I guess all of you have case insensitive filesystems when you ran `npm run build`, right? (Because the build environment runs on a case sensitive filesystem).

**Comment by robertlemke** [comment]
Hmm, it does work on my Mac (case insensitive FS).

**Comment by kdambekalns** [comment]
So for me the last step is not needed!? This is part of the output of `npm install` already:

```> neos-io@0.0.1 postinstall /Users/karsten/Sites/www.neos.io/Packages/Sites/Neos.NeosIo
> cd ../../Application/Neos.MarketPlace && npm install```

**Comment by Sebobo** [comment]
@kdambekalns only if you look at my #125, because I added it there as we had the problem at the sprint and already wanted to fix it. 
So either we merge #125 soon and don't need it here, or we do a separate change.

**Comment by kdambekalns** [comment]
Ok, get it. I noticed it while, looking at #125, exactly. :)

**Comment by Sebobo** [comment]
Ok the marketplace step is not needed anymore now.

**Comment by Sebobo** [comment]
@robertlemke when I look at the projects `.beach.yaml` file it would think this is solved. Can you confirm this?

**Comment by kdambekalns** [comment]
@Sebobo Robert is on vacation right now, but I guess it's solved, yes.
