### ISSUE TITLE
Main page of neos.io/blog.html displays wrong resolution images

### ISSUE THREAD

**Issue by maragi** [neos/Neos.NeosIo#150]
In my Firefox 53 under Win10 as well in Martins Chrome under Mac the startpage of the blog does not load the proper images. The small images are loaded so they look rather pixel-like on the desktop. Berit confirmed that also. It seems like a matter of the responsive implementation.
![neos-blog](https://cloud.githubusercontent.com/assets/7701309/26348150/12f487b0-3fac-11e7-830f-a51a5f5a2d55.png)
https://www.neos.io/blog.html

**Comment by Sebobo** [comment]
Fix didn't solve issue. We have to investigate again.

**Comment by markusguenther** [comment]
<img width="1199" alt="Bildschirmfoto 2019-10-18 um 00 53 34" src="https://user-images.githubusercontent.com/1014126/67053441-c0b89000-f141-11e9-83db-6b94db22858e.png">

Tried it and it seems to work.
