### ISSUE TITLE
Update the show case listing filters

### ISSUE THREAD

**Issue by tobiasgruber** [neos/Neos.NeosIo#153]
To improve the value of the show case listing, the following changes were suggested during the last marketing sprint:

- The label "type" of the filters should be changed to "industry"
- the showcase node type should get a new flag "featured"
- this featured flag should become the default "sort by" option, so when the listing is loaded, the featured show cases are displayed at the top. The other "sort by" options remain and allow to view all show cases

**Comment by mgoldbeck** [comment]
@Sebobo and me discussed about an additional filter for project volume. This would improve the visibility for small and big showcases.

I will add this filter in this change
