### ISSUE TITLE
Minify CSS/JS to improve load speed performance

### ISSUE THREAD

**Issue by manmath** [neos/Neos.NeosIo#156]
There are two files (1 JS and 1 CSS) that do not minify on https://www.neos.io/.

- https://www.neos.io/_Resources ... NeosIo/JavaScript/Bundle.min.js
- https://www.neos.io/_Resources ... ges/Neos.NeosIo/Styles/Main.css

If these two files are  minified we could save up to 81KB.

**Comment by Inkdpixels** [comment]
For anyone who wants to pick this issue up, a minify build step is already available at https://github.com/neos/Neos.NeosIo/blob/master/Packages/Sites/Neos.NeosIo/package.json#L19 so it might be enough to just add it to the Dockerfile/deployment script
