### ISSUE TITLE
Add a feature list to neos.io 

### ISSUE THREAD

**Issue by mficzel** [neos/Neos.NeosIo#173]
I suggest to add a feature list to neos.io (that ideally can be printed) to help convincing companies or decision makers. 

I think for such a page the content and feature-matrix that was already prepared for the cms-garden can be partly reused.

**Comment by maragi** [comment]
we prepared a matrix and a text for cms-garden recently, maybe we can recycle some information...
https://drive.google.com/drive/folders/0Bxv8Bn1cqsv8SWRWc3FjVjZadGc
