### ISSUE TITLE
Add partner list to neos.io

### ISSUE THREAD

**Issue by mficzel** [neos/Neos.NeosIo#174]
Adding an partner list would sometimes help making the decision for using Neos. 

I suggest to list the long-time supporters and list them with:
- Logo (Slightly bigger for higher status)
- Description (Slightly more text for higher status)
- URL 
- Offered Services (SLA, Core Features, Bugfixes, Reviews, Consulting, Projects etc. )

In future this can be made filterable and maybe we can fetch the data via funding api but for now we could just use a manual list/table to get started. Maybe this also helps attracting some more subscription supporters.

**Comment by mficzel** [comment]
An RFC for the topic was discussed here https://discuss.neos.io/t/rfc-neos-agency-listing/3949

**Comment by Sebobo** [comment]
First part was just merged in #284
