### ISSUE TITLE
Deadlinks on https://www.neos.io/about/security-bulletins.html

### ISSUE THREAD

**Issue by klfman** [neos/Neos.NeosIo#181]
https://www.neos.io/about/security-bulletins.html contains five deadlinks (404):
https://www.neos.io/news/neos-sa-2015-002.html
https://www.neos.io/news/neos-sa-2015-001.html
https://www.neos.io/news/flow-sa-2015-001.html
https://www.neos.io/news/flow-sa-2013-001.html
https://www.neos.io/news/flow-sa-2012-001.html

Interestingly, chrome tells me that it can't find these pages (404), Firefox just displays a blank page.

**Comment by bwaidelich** [comment]
Thanks for reporting this, I fixed the links
