### ISSUE TITLE
Editor for property "openInNewTab" not configured

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#194]
When selecting an image an error is raised:

`Couldn't create editor for property "openInNewTab" (no editor configured). Please check your NodeTypes.yaml configuration.`

**Comment by Sebobo** [comment]
@kdambekalns I cannot reproduce this. 
The property comes from `Neos.NodeTypes:LinkMixin` and there it's fully defined.
Maybe this has been resolved in another change in the last months.
