### ISSUE TITLE
BUG: Button Style

### ISSUE THREAD

**Issue by rolandschuetz** [neos/Neos.NeosIo#213]
The button style on neos.io seems to be broken. 

Example:
https://www.neos.io/about/newsletter.html

![bildschirmfoto 2018-06-04 um 16 46 01](https://user-images.githubusercontent.com/735982/40924277-1f483806-6817-11e8-9037-3c4bb546ba10.png)

Tested in Chrome 66 on Mac OS X

**Comment by Sebobo** [comment]
Fixed in #228
