### ISSUE TITLE
Events as NodeTypes with some automation for archiving

### ISSUE THREAD

**Issue by kitsunet** [neos/Neos.NeosIo#255]
Build event NodeTypes to facilitate automation of events list with upcoming/past.

Acceptance criteria:

- [ ] Dedicated NodeType for events
- [ ] lists generated from nodes of this type
- [ ] upcoming / past automatically sorted by start/end date of event

**Comment by bwaidelich** [comment]
possibly we could also add some form that allows people (e.g. meetup organizers) to suggest events that will be generated as hidden nodes

**Comment by bwaidelich** [comment]
Some more ideas after a quick sync with @Sebobo:

#### 1. Overhaul page structure

..to make "Events" landing page more visible, for example like this:

![image](https://user-images.githubusercontent.com/307571/57756056-bc033200-76f2-11e9-9c72-bb8cbcbce0b4.png)

#### 2. Tweak markup & styling

..to improve readability and for SEO

#### 3. Initial "Event" node type schema

example:
```
title
dateStart
dateEnd
location
url
hostName(s)
hostUrl(s)
type (conference, meetup, sprint)
```

#### 4. Initial Event Lists (by type)

#### 5. Initial Event archive

#### 6. (possibly) event suggestion form / email link

**Comment by Sebobo** [comment]
I added to "Upcoming Events" shortcut

**Comment by Sebobo** [comment]
We should use the fields according to schema.org that google recommends https://developers.google.com/search/docs/data-types/event
