### ISSUE TITLE
Setup Google Search Console properties

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#256]
- [x] Add `google-site-verification=iNggBv5RdtCnljnGf4W0quLQvGUgXKC0z-CLo3bh_H0` as TXT record to neos.io

- [x] Add `google-site-verification=Ymfb53CLnwhhxvPL9FwqDS8XhLqs9sD9tddvyZ1mZcc` as TXT record to neoscon.io

- [x] Add `google-site-verification=9DAAvxfJ1h4rxb-tZaE70OhRn0yLVy-2n02q7KrGfqY` as TXT record to flow.neos.io

**Comment by robertlemke** [comment]
@skurfuerst neoscon.io is managed via sandstorm NS – can you apply that configuration?
