### ISSUE TITLE
Animated Gifs are not rendered

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#264]
Vips cannot load the animated Gifs and throws an exception.

The reason is that I had to update rokka/vips to 0.9.0 to make it work with the latest Neos version and it's dependencies. 

But rokka/vips added support for animated gifs in 0.9.0 see https://github.com/rokka-io/imagine-vips/releases/tag/0.9.0

But for this to work, libvips 8.7.0 is needed and we have 8.4.5 on Neos.io.

I don't see any way to prevent the library from loading gifs therefore it seems the only way is to update libvips to 8.7.0

**Comment by kdambekalns** [comment]
Huh, that would mean going to Ubuntu 19.04 as a base, 18.04 (as used by us) only has 8.4.5. Or building it manually…

**Comment by kdambekalns** [comment]
Given the complexity involved, I'll not do this today (i.e. before going on vacation).

I suggest to either switch to using videos insteasd of the GIF files or try again without vips (and use imagick instead).

**Comment by Sebobo** [comment]
Hm too bad. But I can test it on the staging system with imagick.

**Comment by davidspiola** [comment]
@kdambekalns do you think you have time for this in the near future? If not, I would suggest to move back to imagick.

**Comment by kdambekalns** [comment]
It's not about having time, it's about switching the base for your cluster to a new Ubuntu… ;)

But of course we cold go back to imagick, that's just a configuration in the neos.io project. If only I could remember why we switched to VIPS, was there some reason for it, beyond "it's new and (supposed to be) more performant"?

**Comment by bwaidelich** [comment]
Maybe it would be less work (with IMO better results) to switch to videos here as we discussed in https://neos-project.slack.com/archives/C04V4DHEG/p1558358743020600

**Comment by davidspiola** [comment]
ok, I'll create a very basic video embed component. I guess we need it anyway

**Comment by davidspiola** [comment]
FYI: https://github.com/neos/Neos.NeosIo/pull/311

**Comment by regniets** [comment]
Closing this issue since we replaced all the gifs with videos and won't fix it anytime soon...
