### ISSUE TITLE
A version of ocramius/proxy-manager is used which requires PHP 7.4

### ISSUE THREAD

**Issue by robertlemke** [neos/Neos.NeosIo#276]
I just stumbled over the last change which contained an upgrade of ocramius/proxy-manager to version 2.4.0. I guess @Sebobo did run `composer update` with ignoring platform requirements (which, I have to admit, I also did sometimes), and by that the version 2.4.0 of the ocramius/proxy-manager slipped in. We have to be careful with this …

The root cause is, that just doing a `composer update` with PHP 7.3 installed locally won't do on most systems, because we require `libvips`, which most people don't have installed. As a workaround, you can copy a composer.phar into your Local Beach container, run composer update in the container, copy the resulting `composer.lock` to `Data/Persistent`, and then fetch it from there on your host (your computer) and commit it to Git. Not quite elegant, but at least a workaround for the time being.

In the long run, I'd like to provide a good solution for Local Beach, so you can just run `beach composer update`. The biggest issue there is SSH key forwarding using an SSH agent, for example when you use a hardware token like Yubikey. There are no easy solutions for that … but hey, we love challenges, don't we?

**Comment by Sebobo** [comment]
I'll fix this problem in #273 as I'm anyway working on the topic

**Comment by Sebobo** [comment]
You were too fast ! ;)
