### ISSUE TITLE
Incorrect Link to Developer Documentation

### ISSUE THREAD

**Issue by djbrown** [neos/Neos.NeosIo#279]
When I visit the Documentation Overview on https://www.neos.io/docs-and-support.html I can see a Column for "Developers". When I click on the related link "Explore the documentation" my browser navigates to the very same page i already was.
I think the problem is the missing href attribute on the anchor tag..
Should this link navigate to https://docs.neos.io/? Please update the reference , thank you :)

**Comment by djbrown** [comment]
According to the navbar, the link should target docs.neos.io. Also now I found out about https://neos.readthedocs.io. It isn't references anywhere.

**Comment by Sebobo** [comment]
Hi @djbrown,

thanks for creating the issue! I fixed the mentioned link to of course lead to docs.neos.io.

We link to neos.readthedocs.io from several places like at the top menu on docs.neos.io and from https://docs.neos.io/cms/references.

We are in the process of slowly moving the content piece by piece to docs.neos.io.
