### ISSUE TITLE
GoEssential Javascript Error

### ISSUE THREAD

**Issue by markusguenther** [neos/Neos.NeosIo#292]
The go essential Javascript throws an error on neos.io.

<img width="539" alt="Bildschirmfoto 2019-11-05 um 20 37 28" src="https://user-images.githubusercontent.com/1014126/68239924-3199ec00-000c-11ea-8656-0678320e050f.png">

**Comment by Sebobo** [comment]
Would also be good not to include this js file on every page, but only where it's needed. It's quite a bit of JS.

**Comment by Sebobo** [comment]
@davidspiola when do you think you can take a look at the issue?

**Comment by davidspiola** [comment]
I hope today
