### ISSUE TITLE
Improvement suggestions for service provider listing

### ISSUE THREAD

**Issue by lorenzulrich** [neos/Neos.NeosIo#304]
* The search box and filter selects are using Arial. `input` and `select` need to be explicitely targeted by a `font` CSS definition, just defining a `font` for `body` isn't enough.
* It is unclear why the full address is necessary in the table (and why it is in italic). Country and city would be enough IMO and reduce "visual stress".
* Other than suggested by the arrows, you cannot sort in descending direction. The sorting doesn't work correctly for "Size" and doesn't really make sense for "Location" IMO.
* Maybe something like alternating row backgrounds or a line after the header row could improve readability.

**Comment by Sebobo** [comment]
Thx for the input!

We already plan to clean up the table. We will reduce the address to city and country and then the sorting makes more sense again.
Also we plan to sort the services and replace them with icons and tooltips.
With those two changes we have more space for the company name and the table should be cleaner and we can give it more vertical space in each line.

I wasn‘t able to finish the sorting yet but knew I needed the icons to make it more obvious that you can sort. So the sorting direction switch will come soonish.

With real data some things get much more obvious. Also on the detail page of each provider.

**Comment by Sebobo** [comment]
All done now, I think

**Comment by lorenzulrich** [comment]
Great, thank you!
