### ISSUE TITLE
Counter content can break javascript execution

### ISSUE THREAD

**Issue by rolandschuetz** [neos/Neos.NeosIo#306]
The count up javascript isn't very robust. Each component should be initialized within a try-catch, currently, the counter can break the whole page.

Specific counter bugs:

- The counter does not support “>” as prefix or suffic, it’s rendered as “&gt;”
- String to number conversion for the actually number easily breaks without proper error handling, e.g. ” 1000" instead of “1000” or separators like “1.000"

**Comment by Sebobo** [comment]
Created a fix for the number issue but I don't understand the problem with ">". Can you elaborate that further?

**Comment by rolandschuetz** [comment]
When you want that the counter says `>35000 nodes`, the prefix would be `>` and the suffix `nodes`.

But the prefix would be displayed as `&gt;`, since the html encoded content is displayed as text

**Comment by Sebobo** [comment]
Ah then that's fixed now too incidentally.
