### ISSUE TITLE
Package listing is not up-to-date

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#312]
Several packages are missing from the package repo on neos.io.
Others don't have the correct number of stars and downloads.

I tried ~two weeks ago to fix this by running rebuilding the node index but has issues with duplicate properties and then ran out of memory.
After fixing some configurations I still wasn't able to fully reindex.

**Comment by gerdemann** [comment]
On packagist.org our package Avency.Neos.VarDump has 7 stars and 1981 downloads. But on our profile page there are only 3 stars and 11 downloads.
In addition, this package does not appear in the package list.

**Comment by Sebobo** [comment]
So @kitsunet gave the site a larger instance today and the indexing went through. It seems all packages are there again.

But that only solves part of our issue. The number still don't update.
But a quick look into the code showed that package information is only updated when there is also an actual update in the package. So your example didn't get a release for a year and so the information is a year old.

I think this is not so awesome. One way to fix this could be to at least sync when the last sync was a week ago. Then our package information would at the most be 7 days old.

We just have to check whether the sync runs into performance/memory issues then when there is too much to update once a week.

**Comment by gerdemann** [comment]
@Sebobo Unfortunately the number on our service provider page is still not correct.

**Comment by Sebobo** [comment]
@gerdemann did you update your repo?

**Comment by gerdemann** [comment]
@Sebobo No, i did not update the repo.
The numbers of installs and stars are outdated on neos.io.
For example:
https://packagist.org/packages/avency/neos-vardump/stats
and
https://www.neos.io/who-uses-neos/service-providers/avency-gmbh.html

**Comment by Sebobo** [comment]
@gerdemann yes I know. I wrote in the previous comment that it currently only syncs the repo when there was an actual change in the repo. Like a new tag or branch :)

**Comment by gerdemann** [comment]
@Sebobo ah, sorry. Got it wrong somehow. 🙈
