### ISSUE TITLE
Details about Neos Team members cuts in half

### ISSUE THREAD

**Issue by crydotsnake** [neos/Neos.NeosIo#342]
Hello!.

I found a little design bug on the Neos Team page.

OS: MacOS Catalina
Browser: FIrefox

![neos-team](https://user-images.githubusercontent.com/39345336/85951450-8dcacb00-b963-11ea-8278-5ca53f42adc3.png)

**Comment by Sebobo** [comment]
Seems to only sometimes affect Firefox

**Comment by crydotsnake** [comment]
Yes. In Safari and Brave it worked well. Sorry for the bad bug description!.

**Comment by kdambekalns** [comment]
Works fine by now…
