### ISSUE TITLE
Add more spacing for the mobile view

### ISSUE THREAD

**Issue by markusguenther** [neos/Neos.NeosIo#357]
When you reaad the blog on your mobile phone the list view looks bit penetrated because we are missing some spacings at the sides.

So would be nice if we add more spacing on the list view. Like the detail view :) 

![IMG_7948](https://user-images.githubusercontent.com/1014126/90222791-11a21f00-de0d-11ea-8e5b-9d84761b1a96.PNG)

**Comment by regniets** [comment]
You are right, saw this yesterday. We have to adapt the constraints for Post List so it fits into a Stage or Semantic section - had to change it to a landing page...

**Comment by markusguenther** [comment]
Ok that was a fast response :P

**Comment by regniets** [comment]
PR for solving that issue: https://github.com/neos/Neos.NeosIo/pull/361
