### ISSUE TITLE
Remove remaining Google data collection possibilities 

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#368]
- [x] Use local font instead of Google API
- [x] Prevent YouTube from tracking without Opt-In on neos.io homepage, videos page and neoscon homepage
- [x] CSS file from Mailchimp

**Comment by jonnitto** [comment]
@Sebobo I would suggest using [Jonnitto.PrettyEmbedVideoPlatforms](https://github.com/jonnitto/Jonnitto.PrettyEmbedVideoPlatforms)

It has the same capabilities as [Jonnitto.PrettyEmbedYoutube](https://github.com/jonnitto/Jonnitto.PrettyEmbedYoutube), but can handle also Vimeo. The selection of which platform it is is handled automatically by the ID provided in the inspector. This package is the successor of PrettyEmbedVimeo and PrettyEmbedYoutube, merged into one.

**Comment by regniets** [comment]
@jonnitto - how does Jonnitto.PrettyEmbedVideoPlatforms handle the actual video load? 
On page load both on mobile and larger screens? And does it use the youtube-nocookie domain?
Think we need this functionality

**Comment by jonnitto** [comment]
@regniets You can configure it to use the no cookie domain. But the drawback is, that you have to click twice. Another option would be to enable the `enableGdprMessage` option: https://github.com/jonnitto/Jonnitto.PrettyEmbedVideoPlatforms#global-settings-for-the-whole-prettyembed-series
