### ISSUE TITLE
Proper replacement for use_dis_max needed?

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#380]
See https://github.com/neos/Neos.NeosIo/commit/b0cc89874b977e51726c6723290a3ffb36751462#r45694631

**Comment by kdambekalns** [comment]
I'd say a "multi match" query of type "best fields" would be a replacement: https://www.elastic.co/guide/en/elasticsearch/reference/7.10/query-dsl-multi-match-query.html#type-best-fields

**Comment by kdambekalns** [comment]
@daniellienert @regniets What do you think?

**Comment by daniellienert** [comment]
😮 - never used that. Still had no time to properly look into it. Is it similar to https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-dis-max-query.html? 
I really wonder - is our search use case really that special? 

Wouldn't a simple query string be sufficient? It also should support multiple weighted fields?

**Comment by regniets** [comment]
It sounds ok and if it produces good results, it should to the trick at least for the update.
@daniellienert - you are completely right, there is nothing so special about the package search. If you find the time at some point to look into it and set it up in an easier way, it might make upcoming updates more straightforward :)
