### ISSUE TITLE
Packages listing is missing on service provider pages

### ISSUE THREAD

**Issue by jonnitto** [neos/Neos.NeosIo#410]
Since the last update, the packages listing is missing on service provider pages 

![CleanShot 2021-09-15 at 15 03 07@2x](https://user-images.githubusercontent.com/4510166/133438396-70f0b401-b52e-4e58-b0cc-9048d5938f89.png)

**Comment by Sebobo** [comment]
@regniets this is probably due to our reindexing, shouldn't it then have fixed itself by now?

**Comment by regniets** [comment]
@Sebobo - could be a caching issue (didnt figure out how that could happen), but it really seems broken...
Dont think its an index thing, just a regular Flowquery:
https://github.com/neos/Neos.NeosIo/blob/master/DistributionPackages/Neos.NeosIo.ServiceOfferings/Resources/Private/Fusion/Documents/ServiceProvider.fusion#L61

Also if i add additional packages, it wont show up...

**Comment by regniets** [comment]
this should to the trick
https://github.com/neos/Neos.NeosIo/pull/411
