### ISSUE TITLE
Fix the Footer section elements allingnment

### ISSUE THREAD

**Issue by shefali12-ab** [neos/Neos.NeosIo#413]
Hii, I would like to contribute by fixing the alignment of footer section and improving its UI, as the logo and others elements are not allingned perfectly.
![Neos-CMS-Open-Source-Content-Application-Framework-Neos-io](https://user-images.githubusercontent.com/56781823/137591467-76266dd7-dc8a-4030-87bb-4a6e9039c537.png)

**Comment by shefali12-ab** [comment]
@jonnitto Thank you :)

**Comment by Sebobo** [comment]
How about we move the "N" above the bottom text and center it.
