### ISSUE TITLE
Broken package search for certain queries

### ISSUE THREAD

**Issue by kdambekalns** [neos/Neos.NeosIo#415]
Searching for the кeyword `site`  breaks the packages search :boom: Other keywords will return with 0 results.

https://www.neos.io/download-and-extend/packages.html?search=site&version=

![image](https://user-images.githubusercontent.com/95873/146423597-a9ea2dc5-7f0b-473f-9ae4-fd24c9560fee.png)

`Exception while rendering root<Neos.Fusion:Case>/documentType<Neos.Fusion:Matcher>/element<Neos.MarketPlace:RepositoryStorage>/body<Neos.Fusion:Template>/content/main<Neos.Fusion:Join>/marketplace<Neos.MarketPlace:Search>: An invalid node path was specified: is of type NULL but a string is expected.`

Broken:

- site
- package
- object
- resource
- asset
- node
- copy
- …?

Working, giving 0 results:

- quux
- garglpuh

So, it's not about no results, but something else.

Thanks to @paavo for reporting

**Comment by mhsdesign** [comment]
doesnt work:

string

(casing doenst matter)


works:

integer, int, bool, boolean

**Comment by daniellienert** [comment]
It also works for search terms (that are part of the package name?) like "punktde" or "sylius"

**Comment by mhsdesign** [comment]
`types` and `fusion` and `afx` also breaks.

And it breaks not when a breaking keyword is mixed with a non breaking keyword like

`fusion abcdef`

but two breaking keywords break:

`fusion afx`

**Comment by kdambekalns** [comment]
Another interesting bit: a blog post as result :)

<img width="732" alt="image" src="https://user-images.githubusercontent.com/95873/150292300-2fbb2308-c11e-49b0-b0b6-3867ba7b2c89.png">

**Comment by paavo** [comment]
Did someone had time to have a look at this?
Looks pretty bad for "new Developers" if every second search results in a weird error 🤔

**Comment by regniets** [comment]
You're completely right, that has to be fixed soonish.
Also really annoying for existing Devs, it is a very popular page.
I'll have a look into it, if anyone else can check as well, i'd be happy.

**Comment by regniets** [comment]
Hope that fixes it - not quite sure yet (hard to test though, marketplace:sync still a hazzle locally)
https://github.com/neos/Neos.NeosIo/pull/420

**Comment by regniets** [comment]
@kdambekalns @Sebobo @crydotsnake

**Comment by regniets** [comment]
Looks promising. 
@paavo @mhsdesign - if you want to test a little bit and report if you still find any errors?

**Comment by kdambekalns** [comment]
Looks good now, I could not trigger any errors.

**Comment by kdambekalns** [comment]
Thanks @regniets!
