### ISSUE TITLE
NeosDemo: Beach Setup

### ISSUE THREAD

**Issue by regniets** [neos/Neos.NeosIo#439]
Setup demo.neos.io on beach

Relates: #433

**Comment by markusguenther** [comment]
Initial setup is done.
https://github.com/neos/demo.neos.io/compare/e121747a374f0a979473e90a743ba743ffbc1c82...f7f3ccf3be6040098f888d007800880ce96d5ac8

The admin user will be created automatically from beach via environment variables.
The instance is available at demo.neos.io and the credentials for the admin are stored in 1Password.
