### ISSUE TITLE
BUG: Irritating or wrong sorting on case studies overview page

### ISSUE THREAD

**Issue by ahaeslich** [neos/Neos.NeosIo#464]
Is it intended behavouir, that the case studies list can be sorted by `datePublished`? The value is never shown to the user and if you use the sorting option while displaying the entries as table all you reongnize is a sorting by `launchDate`. 

And this will show to the user a broken sorting as seen below:

![image](https://user-images.githubusercontent.com/1756367/202267963-fcf85606-5928-4679-adca-fd9ddf3c499d.png)

Link: https://www.neos.io/who-uses-neos/show-cases.html

**Comment by Sebobo** [comment]
Good question. The idea was to be able to see the latest entries (but then switching to the oldest doesn't make much sense). But I agree it would then be better to show the publish date too, maybe together with the launch date. Wdyt?
