### ISSUE TITLE
EmailAction for forms throws errors

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#474]
Folgender Fehler tritt bei der Vernwendung von `smtp.postmarkapp.com` auf:

```
Expected response code 220 but got an empty response
```

Die gleiche Konfiguration funktioniert bei mir lokal korrekt.

**Comment by Sebobo** [comment]
Port is now correct but problem persists...

**Comment by Sebobo** [comment]
Hi @kdambekalns did you get a chance to check the issue? We would need the forms for some NeosCon topics.

**Comment by kdambekalns** [comment]
@Sebobo / @crydotsnake Fixed now, sending mails works. You can enable anything that needs them now…
