### ISSUE TITLE
Updated: Header Stage

### ISSUE THREAD

**Issue by tschoeki** [neos/Neos.NeosIo#492]
Old:
![Image](https://user-images.githubusercontent.com/6552092/255820808-99c30805-19f3-4c41-87e3-0a1e8cf8ad11.png)

New:
![Image](https://user-images.githubusercontent.com/6552092/255820723-0fdaf288-f860-4422-a623-f52b0035e82a.png)

Update:

- [x] lose the dropshadows on the font
- [x] add slight grey overlay on header image
- [x] font larger (60px)
- [x] make header stage full viewport height

**Comment by tschoeki** [comment]
maybe try Mix-blend-mode to only darken highlights in images

**Comment by regniets** [comment]
Looks good on stage.
