### ISSUE TITLE
TASK: Remove unnecessary nesting, eg content collection

### ISSUE THREAD

**Issue by mhsdesign** [neos/Neos.NeosIo#501]
<img width="293" alt="image" src="https://github.com/neos/Neos.NeosIo/assets/85400359/6b37ff31-3b14-4ad0-a1ae-fd24c4bc85f1">

https://mind-the-seb.de/blog/preventing-deep-content-nesting-in-neos-cms

also update the blog post

example migration:
https://github.com/Unikka/neos-slick/tree/master/Classes/ContentRepository/Transformations

**Comment by Sebobo** [comment]
Fixed
