### ISSUE TITLE
Concept: Service Provider Listing rearranged

### ISSUE THREAD

**Issue by NicoleNitschke** [neos/Neos.NeosIo#504]
## Stakeholder analysis
There are 3 target groups of the service provider listing, both of which want to benefit from the listing:

1. service providers
2. potential Neos customers
3. Neos team

Ideally, the Service Provider Listing will allow each Neos customer to find the service provider that is right for them. This means the filters should be aligned to match customer and provider size.
The Neos team wants support in the form of money or cooperation, with money having a lower barrier to entry and potentially many more agencies investing here if the service provider listing is designed. On the other hand, the most paying agency is not necessarily the best for the client, so the filters must be optimized and targeted accordingly.

## Current state of the service provider listing
Currently the listing displays agencies in random order. All agencies that have a badge for development or payment are displayed first. This is followed by all agencies that do not have a badge.
The order of the service providers changes with every page load - even if you reload the page.
For each agency, the following achievements can be seen in the list:
* Supporter Badge
* Developer Badge
* Neos Awards

Further information in the list are:
* Service types
* Company size
* Headquarter

### Move the Open Street Map under the listing
If you visit the service provider listing in the current state, there is no service provider above the fold. The user has to scroll to come to the list and the filters are more hidden than necessary. It would be better to have the filters and list above the fold and move the map under the list. (If someone misses the map, wie can provide a button 'Find provider by location'.)

### Remove 'Table list' view
The current filter 'Show list in table view' only shows a list of all providers. There are currently 2 buttons reserved for this switch at once, which distract the focus from the filters that are more relevant to the customer.
Instead, there should be only one view that appears clearly on mobile and also on desktop.

### Reposition number of results found
Currently, the number of found results is displayed in the same row as the various filters between interactive elements. This leads to confusion and distracts from the actual filters.
The number of results should be positioned separately instead. Furthermore, the icon is not meaningful. Instead, another icon must be found or the icon is directly replaced by a text, since the result number is placed there separately anyway.

### Search icon should be positioned inside input field
Currently, the search icon is outside the relating input. It has no function either, so it should be placed inside the input to highlight it as search field. There is no need for a button indication or something like this, because there is click functionality. This way, the filter bar would be a little bit cleaner.

#### Example screen of cleaner filters

![grafik](https://github.com/neos/Neos.NeosIo/assets/11499598/7c166063-9412-4a6a-8f34-0af6e98e38a9)

Furthermore, it would be great to povide an icon for each dropdown before its label for a faster orientation.

### Less random arrangement of service providers
The service providers that support Neos the most should also be ranked higher to encourage service providers to support Neos more. If some service providers offer the same support, they should be randomized as already implemented for fairness.
The obvious first: the more a service provider pays, the higher it should be in the list. The order would be as follows:
* Diamond Sponsor
* Platinum Sponsor
* Gold Sponsor
* Silver Sponsor
* Bronze Sponsor

The non-obvious: What about Neos team members? If a service provider has two badges, it should be ranked ahead of service providers with the same supporter level. If a service provider does not have a Supporter badge, but has a Team member badge, it should be ranked equally with a Gold level.
So the final ranking could be:
* Diamond Sponsor + Neos team member
* Diamond Sponsor
* Platinum Sponsor + Neos team member 
* Platinum Sponsor
* Gold Sponsor + Neos team member
* Silver Sponsor + Neos team member
* Bronze Sponsor + Neos team member
* Gold Sponsor / Neos team member only randomized
* Silver Sponsor
* Bronze Sponsor
* others

**Comment by mhsdesign** [comment]
<img width="655" alt="image" src="https://github.com/neos/Neos.NeosIo/assets/85400359/e4d0a303-6bdf-40fd-b839-f8ba2a902acf">

fix styling on safari please ;)

**Comment by NicoleNitschke** [comment]
The discussed results of this tickets are now structured in #517. So this issue for concept can be closed. I would like to implement #517, so it would be nice if someone could assign it to me. :)

**Comment by ahaeslich** [comment]
> it would be nice if someone could assign it to me. :)

and it's yours 🙂
