### ISSUE TITLE
Simplify nodetypes to declutter content tree

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#506]
- [ ] Remove single content collection and move content to the stage itself to cleanup the content tree
- [ ] Make it possible to define the title on the stage itself instead of adding a separate node each time (improved legibility in the tree also)

**Comment by Sebobo** [comment]
Hi @ahaeslich besides cleaning up the collection I also define the title optionally on the stage itself to remove the need for a text node and make it easier to see which stage stands for what in the tree

**Comment by regniets** [comment]
Works as expected on stage!
