### ISSUE TITLE
Moving content in English with subnodes disconnects content in the German version in some cases

### ISSUE THREAD

**Issue by Sebobo** [neos/Neos.NeosIo#523]
* Affects homepage
* Affects migrations and manual movement
* Same as https://github.com/neos/neos-development-collection/issues/3340

Currently investigating...

**Comment by Sebobo** [comment]
Moving manually seems to be fixed by turning every ContentCollection into an aggregate, but still having issues with the migrations

**Comment by mhsdesign** [comment]
i dont understand how this is specific to the neos.io? or isnt it?

**Comment by Sebobo** [comment]
@mhsdesign it's a general Neos problem, see https://github.com/neos/neos-development-collection/issues/3340

**Comment by Sebobo** [comment]
So I have a fix ready, and currently making sure that all migrations and manual tasks work with it. As some content is a bit broken in the CR I have to allow the migrations to continue even if there is a problem, and afterwards resolve those issues by hand based on the output, which shouldn't be too hard.

My plan is too finish the code changes, update neos.io staging to the live db, run everything there, make sure that the German version works and then move on to live.
